name: Step level Env Example

on:
  workflow_dispatch:

jobs:
  demo:
  runs-on: ubuntu-latest

Steps:
  - name: step level example
  env:
    CITY: Hyderabad
    TRAINER: TVS
  run: |
    echo "city is $CITY"
    echo "Trainer is $TRAINER"

  - name: next step
    run: echo "City is $CITY and trasfer is $TRAINER"
